services:
  v:
    image: khalyomede/vlang:latest-alpine
    user: root
    entrypoint: v
    working_dir: /root/app
    volumes:
      - .:/root/app

  v0412:
    image: khalyomede/vlang:0.4.12-alpine
    user: root
    entrypoint: v
    working_dir: /root/app
    volumes:
      - .:/root/app
